# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rmonitor.proto\"\x18\n\x07\x43puLoad\x12\r\n\x05value\x18\x01 \x01(\x02\"\x1a\n\x08Response\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t23\n\x0eMachineMonitor\x12!\n\x08\x63heckCpu\x12\x08.CpuLoad\x1a\t.Response\"\x00\x62\x06proto3')
)




_CPULOAD = _descriptor.Descriptor(
  name='CpuLoad',
  full_name='CpuLoad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='CpuLoad.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=41,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='Response.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['CpuLoad'] = _CPULOAD
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CpuLoad = _reflection.GeneratedProtocolMessageType('CpuLoad', (_message.Message,), dict(
  DESCRIPTOR = _CPULOAD,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:CpuLoad)
  ))
_sym_db.RegisterMessage(CpuLoad)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)



_MACHINEMONITOR = _descriptor.ServiceDescriptor(
  name='MachineMonitor',
  full_name='MachineMonitor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=71,
  serialized_end=122,
  methods=[
  _descriptor.MethodDescriptor(
    name='checkCpu',
    full_name='MachineMonitor.checkCpu',
    index=0,
    containing_service=None,
    input_type=_CPULOAD,
    output_type=_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINEMONITOR)

DESCRIPTOR.services_by_name['MachineMonitor'] = _MACHINEMONITOR

# @@protoc_insertion_point(module_scope)
