# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import monitor_pb2 as monitor__pb2


class MachineMonitorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.checkCpu = channel.unary_unary(
        '/MachineMonitor/checkCpu',
        request_serializer=monitor__pb2.CpuLoad.SerializeToString,
        response_deserializer=monitor__pb2.Response.FromString,
        )


class MachineMonitorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def checkCpu(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MachineMonitorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'checkCpu': grpc.unary_unary_rpc_method_handler(
          servicer.checkCpu,
          request_deserializer=monitor__pb2.CpuLoad.FromString,
          response_serializer=monitor__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MachineMonitor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
